eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #instance:
   # hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order
  produk-service:
    endpoints:
      endpoint:
        uri: http://PRODUK-SERVICE/produk
  email-service:
    endpoints:
      endpoint:
        uri: http://EMAIL-SERVICE/email      
